### PR TITLE
Bootstrap 3 like events

### PR DESCRIPTION
**Pull request by wwebfor**
Without this triggers (hidden.bs.modal) script will not remove content from DOM.

### CODE REVIEW

**Comment by powmedia** [comment]
Is this replacing your previous pull request?

Also can you explain why you've renamed the events? Thanks

**Comment by wwebfor** [comment]
Because in TW Bootstrap 3 events like shown, hiden has been renamed to shown.bs.modal and hidden.bs.modal.

http://getbootstrap.com/javascript/#modals

**Comment by powmedia** [comment]
I can't get the shown.bs.modal event to fire, is it working for you?

**Comment by ihortymoshenko** [comment]
@powmedia, it works for me, can you merge? :)

**Comment by powmedia** [comment]
The bootstrap3 branch is using these events (but still triggering the standard 'shown' and 'hidden' events on the Backbone.Modal object).  If that's all working for you I'll merge that into master.

**Comment by ihortymoshenko** [comment]
@powmedia, ok, let's do it. It won't break `Backbone.BootstrapModal` API

**Comment by powmedia** [comment]
That's been merged in to master, closing

**Pull request closed without merging**
